import { BlockingSheetType } from './additions/blockingSheet';
import { InsecticideCocktailPart } from './additions/insecticideCocktailPart';
import { LatexRemoverType } from './additions/latexRemover';
import { MettoLabelType } from './container/mettoLabel';
import { SealType } from './container/seal';
import { StapleType } from './container/staple';
import { StrippingType } from './container/stripping';
import { ThermographType } from './container/thermograph';
import { BandType } from './materials/band';
import { ClusterBagType } from './materials/clusterBag';
import { LabelType } from './materials/label';
import { ProtectorType } from './materials/protector';
import { RubberType } from './materials/rubber';
import { SachetType } from './materials/sachet';
import { PesticideCocktailPart } from './post-harvest/pesticideCocktailPart';
import { BrandType } from './specifications/brand';

export type BoxBrandType = {
  id?: number | '';
  // specifications
  brand?: Partial<BrandType>;
  brandId: number | '';
  name: string;
  brandCode: string;
  boxQuantity: number | '';
  netWeightBox: number | '';
  grossWeightBox: number | '';
  requiredCertificates: number[] | null | string[];
  // materials
  bottomTypeId: number | '';
  bottomTypeQuantity: number | '';
  lidTypeId: number | '';
  lidTypeQuantity: number | '';
  coverTypeId: number | '';
  coverTypeQuantity: number | '';
  cardboardTypeId: number | '';
  cardboardTypeQuantity: number | '';
  parasealTypeId?: number | '';
  parasealTypeQuantity: number | '';
  padTypeId?: number | '';
  padTypeQuantity: number | '';
  spongeTypeId?: number | '';
  spongeTypeQuantity: number | '';

  label?: Partial<LabelType>;
  labelId: number | '';
  labelQuantity: number | '';
  band?: Partial<BandType>;
  bandId: number | '';
  bandQuantity: number | '';
  sachet?: Partial<SachetType>;
  sachetId: number | '';
  sachetQuantity: number | '';
  rubber?: Partial<RubberType>;
  rubberId: number | '';
  rubberQuantity: number | '';
  protector?: Partial<ProtectorType>;
  protectorId: number | '';
  protectorQuantity: number | '';
  clusterBag?: Partial<ClusterBagType>;
  clusterBagId: number | '';
  clusterBagQuantity: number | '';
  // post harvest
  pesticideCocktail?: Partial<PesticideCocktailPart>[];
  palletsTypeId?: number | '';
  palletsTypeQuantity: number | '';
  miniPalletsTypeId?: number | '';
  miniPalletsTypeQuantity: number | '';
  cornerTypeId?: number | '';
  cornerTypeQuantity: number | '';
  reinforcementTypeId?: number | '';
  reinforcementTypeQuantity: number | '';

  staple?: Partial<StapleType>;
  stapleId: number | '';
  stapleQuantity: number | '';
  stripping?: Partial<StrippingType>;
  strippingId: number | '';
  strippingQuantity: number | '';
  thermograph?: Partial<ThermographType>;
  thermographId: number | '';
  thermographQuantity: number | '';
  seal?: Partial<SealType>;
  sealId: number | '';
  sealQuantity: number | '';
  mettoLabel?: Partial<MettoLabelType>;
  mettoLabelId: number | '';
  mettoLabelQuantity: number | '';
  // additions
  packingTapeTypeId?: number | '';
  packingTapeTypeQuantity: number | '';

  latexRemover?: Partial<LatexRemoverType>;
  latexRemoverId: number | '';
  latexRemoverQuantity: number | '';
  blockingSheet?: Partial<BlockingSheetType>;
  blockingSheetId: number | '';
  blockingSheetQuantity: number | '';
  insecticideCocktail?: Partial<InsecticideCocktailPart>[];
};
